# Generated by Django 2.2 on 2022-03-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautido_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girl',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautido_app.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='photo',
            field=models.ImageField(upload_to='photos/%y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
