# Generated by Django 2.2 on 2022-04-23 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beautido_app', '0003_auto_20220421_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_number', models.IntegerField(verbose_name='Оценка')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautido_app.Girl', verbose_name='Девушка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
